version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nyc_taxi_postgres
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: nyc_taxi_adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
